### ISSUE TITLE
Publish to npmjs?

### ISSUE THREAD

**Issue by arve0** [Versal/react-element#6]
Care to publish to npmjs?

**Comment by possibilities** [comment]
We could, but I don't believe we use this at all. Is that true @mereskin @rjz ? If not maybe it makes more sense to fork or I could transfer the repo over to you or your org?

**Comment by rjz** [comment]
> I don't believe we use this at all.

Agreed.

**Comment by possibilities** [comment]
@arve0 that's good enough for me, let me know if you want me to transfer it somewhere or can help in some other way.

**Comment by arve0** [comment]
Thanks for the quick response. I can fork for now and install from github. I'll let you know if it fits my needs, then I can adopt the maintenance.
